### ISSUE TITLE
Text appears under the toast box in modal pages on iOS 13

### ISSUE THREAD

**Issue by HappyIosDeveloper** [tattn/TTToast#1]
Hi,

Long time no see !!! after 4 years I'm using this perfect library & now I have this issue.

Now on iOS 13 when we toast, Text appears under the toast box in modal pages...

**Comment by HappyIosDeveloper** [comment]
Here is a temporary solution for it.

on TTToast.swift

replace this line:

` msgLabel.center = parent.convert(center, to: self)`

with this:

`   if #available(iOS 13.0, *) {
            let labelCenter = parent.convert(center, to: self)
            msgLabel.center.x = labelCenter.x
            msgLabel.center.y = bounds.midY
        } else {
            msgLabel.center = parent.convert(center, to: self)
        }`

**Comment by tattn** [comment]
Thank you for using this library! 😄 
I didn't know the problem, I'll check later. And thank you for your solution. 👍
